Migrate music_test.js
rvilarl/vexflow pull request #4
Opened 2021-03-17 19:20 UTC by rvilarl

2021-03-19 18:37 UTC, wassertim requested changes

2021-03-19 18:37 UTC, wassertim commented on Gruntfile.js
> +  function webpackConfig(target, entry, preset, mode) {
is preset still used?

2021-03-19 18:37 UTC, wassertim commented on Gruntfile.js
> +  const webpackProd = webpackConfig(TARGET_MIN, MODULE_ENTRY, ['@babel/preset-env'], 'production');
we should remove babel, we don't use it anymore, we use typescript

2021-03-19 18:37 UTC, wassertim commented on Gruntfile.js
> +  const webpackTest = webpackConfig('vexflow-tests-ts.js', path.join(BASE_DIR, 'tests/index.ts'), ['@babel/preset-env'], 'development');
why does the 1st parameter have this strange name?

2021-03-19 18:37 UTC, wassertim commented on Gruntfile.js
> +      files: ['tests/flow.html', 'tests/flow_ts.html'],
why is new flow_ts needed?

2021-03-19 21:26 UTC, rvilarl commented on Gruntfile.js
> +  function webpackConfig(target, entry, preset, mode) {
It is used but I do not know what for

2021-03-19 21:27 UTC, rvilarl commented on Gruntfile.js
> +  const webpackProd = webpackConfig(TARGET_MIN, MODULE_ENTRY, ['@babel/preset-env'], 'production');
Well I wanted to leave the javascript part as untouched as possible

2021-03-19 21:29 UTC, rvilarl commented on Gruntfile.js
> +      files: ['tests/flow.html', 'tests/flow_ts.html'],
In order to check the ts tests, as discussed I decided to leave js as it is in order to keep  the number of changes to a minimum

2021-03-19 21:31 UTC, rvilarl commented on Gruntfile.js
> +  const webpackTest = webpackConfig('vexflow-tests-ts.js', path.join(BASE_DIR, 'tests/index.ts'), ['@babel/preset-env'], 'development');
I left the constant names untouched. vexflow-tests-ts.js is the compiled version of the ts tests. Please note that this is vexflow-tests.js for the js tests.

2021-03-19 21:37 UTC, rvilarl commented
@wassertim I suggest not to spend too much trying to bring both tests together. I mean js and ts tests.

This is an itemediate step and there is not much difference in the output and you still get a summary:

![image](https://user-images.githubusercontent.com/22865285/111844517-796c9b00-8903-11eb-8cde-6c132a747a64.png)

2021-03-19 21:38 UTC, rvilarl commented
This also gives a view on the current progress! :)

2021-03-20 05:14 UTC, rvilarl commented on Gruntfile.js
> +  function webpackConfig(target, entry, preset, mode) {
It was the preset environment for babel. No longer needed and removed

2021-03-20 05:15 UTC, rvilarl commented on Gruntfile.js
> +  const webpackProd = webpackConfig(TARGET_MIN, MODULE_ENTRY, ['@babel/preset-env'], 'production');
Babel removed.

2021-04-02 08:18 UTC, closed without merging